// 🏪 Configuración del Servidor - Fast API
export const RestaurantConfig = {
  NOMBRE_RESTAURANTE: "Fast API Server",
  TELEFONO_RESTAURANTE: "2479-5555",
  DIRECCION_CORTA: "Centro de Heredia, 100m este de la Municipalidad",
  GOOGLE_MAPS_URL: "https://maps.google.com/?q=9.998,-84.113",
  HORARIO: "Lunes a Domingo: 11:00 AM - 9:00 PM",

  PALABRAS_CLAVE_RESTAURANTE: [
    "menu",
    "menú",
    "carta",
    "comida",
    "comer",
    "platillo",
    "plato",
    "dish",
    "sushi",
    "nigiri",
    "sashimi",
    "maki",
    "roll",
    "california",
    "philadelphia",
    "tempura",
    "uramaki",
    "chirashi",
    "entrada",
    "aperitivo",
    "principal",
    "postre",
    "bebida",
    "drink",
    "sake",
    "cerveza",
    "beer",
    "pedir",
    "pedido",
    "order",
    "ordenar",
    "comprar",
    "llevar",
    "delivery",
    "domicilio",
    "reservar",
    "reserva",
    "mesa",
    "table",
    "booking",
    "precio",
    "cost",
    "costo",
    "cuánto",
    "cuanto",
    "barato",
    "caro",
    "expensive",
    "cheap",
    "horario",
    "hora",
    "abierto",
    "cerrado",
    "open",
    "close",
    "schedule",
    "ubicación",
    "ubicacion",
    "dirección",
    "direccion",
    "donde",
    "where",
    "location",
    "address",
    "teléfono",
    "telefono",
    "phone",
    "llamar",
    "contactar",
    "contact",
    "japonesa",
    "japanese",
    "asian",
    "asiática",
    "asiatica",
    "oriental",
    "arroz",
    "rice",
    "pescado",
    "fish",
    "salmon",
    "salmón",
    "atún",
    "atun",
    "tuna",
    "aguacate",
    "avocado",
    "pepino",
    "cucumber",
    "nori",
    "alga",
    "sumo",
    "restaurant",
    "restaurante",
    "local",
    "lugar",
  ],
} as const;
